### ISSUE TITLE
Translated menu elements have wrong references

### ISSUE THREAD

**Issue by mxpgmbh** [CodersCare/l10nmgr#16] opened 2023-06-21 09:56 UTC
If a tt_content element of any menu type (e.g., `menu_pages`), is translated and imported the referenced pages are the translated pages but not the original pages.

When translating a menu element, TYPO3 requires the original page ids as references and will link to the correct pages in the frontend automatically. But if pids of the translated pages are referenced, no pages are listed in the menu element.

**Comment by Bunnyfield** [comment] 2023-06-27 09:37
Since IDs are numerical values, which should not be translated at all, they are usually not touched by the L10nmgr process, because the translators can not know the IDs beforehand.

If there are changes in the values, this means, they are caused by the DataHandler process, which is a job of the TYPO3 core.

So I will close the issue here and you should open it in the core tracker.
If you got additional evidence that this is still caused by L10nmgr, feel free to reopen the issue.

**Closed** 2023-06-27 09:37 UTC
