### ISSUE TITLE
PHP warning on import: undefined array key "pi_flexform" 

### ISSUE THREAD

**Issue by derBoogie** [CodersCare/l10nmgr#32] opened 2023-07-12 13:05 UTC
After the update of l10nmgr to version 1.0.0 with TYPO3 11.5.29 I'm getting multiple PHP warnings at import: undefined array key "pi_flexform" in ../l10nmgr/Classes/Model/L10nBaseService.php line 792.

**Comment by Konafets** [comment] 2023-07-12 13:38
Duplicate of https://github.com/CodersCare/l10nmgr/issues/29

**Closed by Konafets** 2023-07-12 13:38 UTC
Labels: duplicate
